# PowerShell
# shell = "C:/Users/Sun/AppData/Local/Microsoft/WindowsApps/Microsoft.PowerShell_8wekyb3d8bbwe/pwsh.exe"
# working_directory = "C:/Users/Sun"

# WSL2
shell = "C:/WINDOWS/system32/wsl.exe -d Ubuntu"
working_directory = "//wsl.localhost/Ubuntu/home/tony"
live_config_reload = true

[env]
TERM = "xterm-256color"

[scrolling]
multiplier = 3

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[cursor]
blink_interval = 750
unfocused_hollow = true
style = { blinking = "Always", shape = "Beam" }

[window]
title = "shell"
dynamic_title = false
decorations = "None"
dynamic_padding = true
opacity = 1
startup_mode = "Windowed"
dimensions = { columns = 120, lines = 40 }
padding = { x = 2, y = 2 }

[colors]
bright = { black = "#4c566a", blue = "#81a1c1", cyan = "#8fbcbb", green = "#a3be8c", magenta = "#b48ead", red = "#bf616a", white = "#eceff4", yellow = "#ebcb8b" }
indexed_colors = [{ color = "#242831", index = 16 }]
cursor = { cursor = "#d8dee9", text = "#041419" }
dim = { black = "#373e4d", blue = "#68809a", cyan = "#6d96a5", green = "#809575", magenta = "#8c738c", red = "#94545d", white = "#aeb3bb", yellow = "#b29e75" }
normal = { black = "#3b4252", blue = "#81a1c1", cyan = "#88c0d0", green = "#a3be8c", magenta = "#b48ead", red = "#bf616a", white = "#e5e9f0", yellow = "#ebcb8b" }
primary = { background = "#041419", dim_foreground = "#a5abb6", foreground = "#d8dee9" }
search.matches = { background = "#88c0d0", foreground = "CellBackground" }
selection = { background = "#4c566a", text = "CellForeground" }
vi_mode_cursor = { cursor = "#d8dee9", text = "#041419" }

[font]
size = 13
glyph_offset = { x = 0, y = 0 }
normal = { family = "BlexMono Nerd Font" }
bold = { family = "BlexMono Nerd Font" }
italic = { family = "BlexMono Nerd Font" }
bold_italic = { family = "BlexMono Nerd Font" }

[[mouse.bindings]]
action = "Copy"
mouse = "Forward"

# bindings = [{ <key>, <mods>, <mode>, <action> | <chars> },]
[keyboard]
bindings = [
    #  font size change
    { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },

    # copy & paste
    { key = "Y", mods = "Control", action = "Copy" },      # normal mode
    { key = "P", mods = "Control", action = "Paste" },
    { key = "Y", mode = "Vi", action = "Copy" },           # vim mode
    { key = "Y", mode = "Vi", action = "ClearSelection" }, # after yank in vim mode , clear selection
    { key = "P", mode = "Vi", action = "Paste" },


    # VIM MODE
    # toggle vim mode
    { key = "Space", mods = "Control", action = "ToggleViMode" },
    { key = "Space", mods = "Control", mode = "Vi", action = "ScrollToBottom" }, # after exit vim mode, scroll to bottom
    # Selection
    { key = "V", mods = "Shift", mode = "Vi", action = "ToggleLineSelection" },
    { key = "Escape", mode = "Vi", action = "ClearSelection" },
    # Scroll
    { key = "U", mods = "Control", mode = "Vi", action = "ScrollHalfPageUp" },
    { key = "D", mods = "Control", mode = "Vi", action = "ScrollHalfPageDown" },

    { key = "B", mode = "Vi", action = "SemanticLeft" },
    { key = "W", mode = "Vi", action = "SemanticRight" },
    { key = "E", mode = "Vi", action = "SemanticRightEnd" },
    { key = "B", mods = "Shift", mode = "Vi", action = "WordLeft" },
    { key = "W", mods = "Shift", mode = "Vi", action = "WordRight" },
    { key = "E", mods = "Shift", mode = "Vi", action = "WordRightEnd" },
    # Search
    { key = "Slash", mode = "Vi", action = "SearchForward" },
    { key = "N", mode = "Vi", action = "SearchNext" },
    { key = "Slash", mods = "Shift", mode = "Vi", action = "SearchBackward" },
    { key = "N", mods = "Shift", mode = "Vi", action = "SearchPrevious" },
]
